USE [ArtPostingsTest]
GO
DELETE FROM [dbo].[ArtPostingItems] WHERE Archive_flag = 1
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Jubilaire.jpg', 0, 'Jubilaire','Jubilaire','Jubilaire','Abstract  design of two acrobatically dancing  figures. Acrylic paint on wood panel.','137 x 130 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Paprika.jpg', 1, 'Paprika','Paprika','Paprika','An abstract painting . Acrylic paint on a deep profile canvas.','102 x 76 x 4cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Golden Storm.jpg', 2, 'Golden Storm','Golden Storm','Golden Storm','Impressionist painting. Acrylic paint on canvas with a 15 mm profile.','101 x 80 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Fauna 1.jpg', 3, 'Fauna 1','Fauna 1','Fauna 1','An abstract painting. Acrylic paint on deep profile canvas.','40 x 30 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Fauna 2.jpg', 4, 'Fauna 2','Fauna 2','Fauna 2','An abstract painting. Acrylic paint on deep profile canvas.','40 x 30 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Water Lilies 14.jpg', 5, 'Water Lilies 14','Water Lilies 14','Water Lilies 14','A large impressionist painting. Acrylic Paint on canvas with a 15 mm profile.','127 x 102 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Flame Trees.jpg', 6, 'Flame Trees','Flame Trees','Flame Trees','Acrylic paint on textured surface. Painted on canvas with 15mm profile.','101 x 80 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Praxinus.jpg', 7, 'Praxinus','Praxinus','Praxinus','Acrylic paint on canvas with 15mm profile.','101 x 80 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Joanne''s Poppies.jpg', 8, 'Joanne''s Poppies','Joanne''s Poppies','Joanne''s Poppies','Acrylic paint on canvas-covered board, profile 3cm.','76 x 76 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Travaganza.jpg', 9, 'Travaganza','Travaganza','Travaganza','Abstract painting, conveying joy and celebration. Acrylic paint on canvas with a 4cm profile.','127 x 102 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Blue River.jpg', 10, 'Blue River','Blue River','Blue River','Impression of a rainy evening beside the Thames. Oil paint on canvas with a 4cm profile.','40 x 40 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Glorious Summer.jpg', 11, 'Glorious Summer','Glorious Summer','Glorious Summer','View of a summer garden. Acrylic paint on canvas with a 4 cm profile.','61 x 46 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Bunting.jpg', 12, 'Bunting','Bunting','Bunting','Painting inspired by the Jubilee. Acrylic paint on canvas with a 15 mm profile.','76 x 61 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Jubilee.jpg', 13, 'Jubilee Jesting','Jubilee Jesting','Jubilee Jesting','Abstract painting. Acrylic paint on canvas with a 4 cm profile.','102 x 76 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Colour of Summer.jpg', 14, 'Colour of Summer','Colour of Summer','Colour of Summer','Impression of a summer sunset. Oil paint on canvas with a 4cm profile.','40 x 40 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Oberon''s Dream.jpg', 15, 'Oberon''s Dream','Oberon''s Dream','Oberon''s Dream','An impressionist painting in glorious colours. Acrylic paint on canvas with a 15 mm profile.','','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('A Forest Dream.jpg', 16, 'A Forest Dream','A Forest Dream','A Forest Dream','A large impressionist painting in glorious colours. Acrylic paint on canvas with a 15 mm profile.','127 x 102 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Arboretum.jpg', 17, 'Arboretum','Arboretum','Arboretum','A large impressionist-abstract painting in imaginative, glorious colours.','127 x 102 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Ganza ganza.jpg', 18, 'Ganza ganza','Ganza ganza','Ganza ganza','Abstract painting, conveying joy and celebration. Acrylic paint on canvas with a 15 mm profile.','120 x 40 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Juniper.jpg', 19, 'Sweet Juniper','Sweet Juniper','Sweet Juniper','Painting of figure with abstract design. Acrylic on wood panel.','','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Water Lilies 12.jpg', 20, 'Water Lilies 12','Water Lilies 12','Water Lilies 12','Impressionist painting inspired by Monet. Acrylic paint on canvas with a 3 cm profile.','76 x 76 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Water Lilies 5.jpg', 21, 'Water Lilies 5','Water Lilies 5','Water Lilies 5','Impressionist painting. Acrylic paint on wood panel with a 4cm profile.','76 x 68cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('Trees Fantastic 2.jpg', 22, 'Trees Fantastic','Trees Fantastic','Trees Fantastic','A large impressionist painting in glorious colours. Acrylic paint on canvas with a 15 mm profile.','127 x 102 cm','No longer for sale',1)
INSERT INTO [dbo].[ArtPostingItems] ([Filename],[Order],[Title],[Shortname],[Header],[Description],[Size],[Price],[Archive_flag])
     VALUES('E Lincs Landscape.jpg', 23, 'East Lincolnshire Landscape','East Lincolnshire Landscape','East Lincolnshire Landscape','Impression of the Fens. Oil paint on canvas with a 4cm profile.','40 x 40 cm','No longer for sale',1)
